создал ветку и сделал изменения в Class
Alex8185/myfirstprogect pull request #4
Opened 2020-11-29 20:16 UTC by Alex8185

1. У классов  Chair,  Cupboard, Mixer, Skinali, Table, я командирским решением определил общий метод  standing. 
Т.к. я подразумеваю, что эти классы может связывать общий метод, а именно – все они могут стоять. (согласен, грустный метод, но что еще можно применить к мебели, мне это пришло в голову, сделать standing – как метод)
 Т.е. я выделил абстрактный класс Stand (да, правильней его можно было бы назвать СтоЯщие вещи (WorthwhileThings) например) и сделал классы  Chair,  Cupboard, Mixer, Skinali, Table его производными классами. Они наследуют его метод. 
!!! Как вариант, более приближенный к классике вместо класса Stand я могу сделать класс Мебель (Furniture), определить общие поля или методы  и объединить мебель в производных классах. Я это понимаю, НО мне уже непосебе от мысли. Что придется придумывать общие поля к Шкафу, Стулу и Столу например или общие методы. 
Именно поэтому у меня они, просто в учебных целях, объединены дебильным методом standing.
 И еще, исходя из логики, этот метод можно было бы распространить и на некоторые другие классы,  Cup например. Но я просто ограничил и решил не распространять действие этого метода на другие классы исходя из никаких соображений.)))))

2. Почему он абстрактный? Потому что напрямую от класса Stand я объекты создавать не буду. Поэтому я сделал его абстрактным.

2020-11-30 09:51 UTC, Alexis220382 requested changes
Надо исправить

2020-11-30 09:51 UTC, Alexis220382 commented on src/suboch/Stand.java
> +public abstract class Stand {
Мы обсуждали голосом, название класса Stand не очень хорошо подходит к описанию группы объектов

2020-11-30 09:51 UTC, Alexis220382 commented on src/suboch/Stand.java
> +    abstract void standing();//в тикете объяснил
А вот поведение `stand()` у какой-то группы объектов - это норм

2020-11-30 15:00 UTC, Alex8185 commented on src/suboch/Stand.java
> +public abstract class Stand {
Теперь название класса подходит к описанию группы объектов

2020-11-30 15:11 UTC, Alex8185 commented on src/suboch/Stand.java
> +    abstract void standing();//в тикете объяснил
Ну и stand() поправил

2020-11-30 15:21 UTC, Alexis220382 requested changes

2020-11-30 15:21 UTC, Alexis220382 commented on src/suboch/Test.java
> +        StandingFurniture Table = new Table();
названия переменных пишутся с маленькой буквы

2020-11-30 15:21 UTC, Alexis220382 commented on src/suboch/Table.java
> +public class Table extends StandingFurniture {
Ну это ХОТЬ существительное. Звучит однозначно лучше 😄

2020-12-01 10:50 UTC, Alexis220382 approved these changes

2020-12-01 10:51 UTC, merged