Добавил в тело метода реализацию
Alex8185/myfirstprogect pull request #5
Opened 2020-11-29 22:21 UTC by Alex8185

В абстрактном классе может быть и обычный метод, но если хотя бы один метод абстрактный, то класс обязан быть абстрактным. 
В моем случае я «гуляуся» с методами и просто не помню, почему не вписал в тело метода какую-нибудь реализацию. 
Скорее всего я не знал, как она повлияет и на что, поэтому увидев, что класс компилируется и с пустым телом, так и оставил, забыв спросить и не доделав. 
На данный момент  уже вписал реализацию, но как выше сказал, не понимаю, нужна ли она тут. 
Правильней будет, сделать метод тоже абстрактным и не парится, но в учебных целях хотелось «пагуляцца»…

2020-11-30 09:47 UTC, Alexis220382 requested changes

2020-11-30 09:47 UTC, Alexis220382 commented on src/suboch/Fly.java
> +        System.out.println("Опять этот гребанный домовой");
Содержание поведения ну никак не соответствует его наименованию

2020-11-30 15:30 UTC, Alexis220382 requested changes

2020-11-30 15:30 UTC, Alexis220382 commented on src/suboch/Fly.java
> +        System.out.println("Предметы взлетели и опустились на место");
А когда и в каком случае этот метод будет вызван?
Когда будет вызвана реализация в наследниках этого класса, я понимаю, а когда реализация из абстрактного - не понимаю

2020-12-01 14:34 UTC, Alexis220382 requested changes

2020-12-03 08:34 UTC, Alex8185 commented on src/suboch/Pasta.java
> +    public static void nameFood() { // етод "назвать еду" - глагол
В этом пулл реквесте из неустраненных недостатков было только убрать комментарии к методам, что это глагол. Апрувь.

2020-12-03 08:42 UTC, Alexis220382 commented on src/suboch/food/Cake.java
> +public class Cake {
А это замечание отработано?

2020-12-03 08:42 UTC, Alexis220382 commented on src/suboch/food/Pasta.java
> +public class Pasta {
А это отработано?

2020-12-03 08:43 UTC, Alexis220382 commented
Ни одного коммента не зарезолвлено. Кнопки на коммента понажимай, я же вчера просил

2020-12-03 08:44 UTC, Alexis220382 commented on src/suboch/Pasta.java
> +    public static void nameFood() { // етод "назвать еду" - глагол
Не только

2020-12-03 09:28 UTC, Alex8185 commented on src/suboch/food/Cake.java
> +public class Cake {
Отработал

2020-12-03 09:29 UTC, Alex8185 commented on src/suboch/food/Pasta.java
> +public class Pasta {
Отработал

2020-12-03 09:29 UTC, Alex8185 commented on src/suboch/Cake.java
> +    public static void nameFood() { //метод "назвать еду" - глагол
Убрал

2020-12-03 09:30 UTC, Alex8185 commented on src/suboch/Pasta.java
> +    public static void nameFood() { // етод "назвать еду" - глагол
Ой сё...

2020-12-03 10:18 UTC, Alex8185 commented on src/suboch/Fly.java
> +        System.out.println("Опять этот гребанный домовой");
Изменено

2020-12-03 10:37 UTC, Alex8185 commented on src/suboch/Fly.java
> +        System.out.println("Предметы взлетели и опустились на место");
Я его абстрактным сделал, вопрос отпал

2020-12-03 11:04 UTC, Alexis220382 approved these changes

2020-12-03 11:49 UTC, merged