Распределил проект по пакетам
Alex8185/myfirstprogect pull request #7
Opened 2020-11-29 23:48 UTC by Alex8185

Распределил проект по пакетам

2020-11-30 09:46 UTC, Alexis220382 requested changes
Маленькие нюансы, в общем не плохо

2020-11-30 09:46 UTC, Alexis220382 commented on src/suboch/Test.java
> +import suboch.abstract_classes.Stand;
Название пакета через underline писать не стоит. Старайся, чтобы название пакета состояло из одного слова.
Плюс ко всему не используй в названиях пакетов технические термины, мы помещаем объекты в их как бы боксы по логическим названиям, но не по техническим или ты поместишь все абстрактные классы проекта в один пакет и запутаешься. `dishes`, `furniture` отличные названия

2020-11-30 09:46 UTC, Alexis220382 commented on src/suboch/Test.java
>          System.out.println("hkgvjgcjgv");
😄

2020-11-30 09:46 UTC, Alexis220382 commented on src/suboch/edible/Pasta.java
> +package suboch.edible;
Какое-то ну уж очень странное название пакета edible. Пакет - это собирательное название, не наречие, не глагол, ни прилагательное, НО существительное

2020-12-01 22:08 UTC, Alexis220382 approved these changes

2020-12-02 15:41 UTC, Alexis220382 requested changes

2020-12-02 15:41 UTC, Alexis220382 commented on src/suboch/furniture/StandingObjects.java
> +public abstract class  StandingObjects {
Что такое проиндексировал? Я вижу только то, что добавлен ненужный пробел.

И еще одна просьба, поменяй пожалуйста со множественного на единственное число, когда начнешь изучать коллекции будет более понятно почему я прошу это сделать.

2020-12-02 16:01 UTC, Alex8185 commented on src/suboch/furniture/StandingObjects.java
> +public abstract class  StandingObjects {
А до push я его и не видел, я чисто по цвету в IDE понял, что он какого то х. не под... ...  "в нем есть незафиксированные локальные изменения")))

2020-12-02 16:23 UTC, Alexis220382 approved these changes

2020-12-02 17:58 UTC, merged