Заменил существительное в методе глаголом
Alex8185/myfirstprogect pull request #8
Opened 2020-11-30 00:24 UTC by Alex8185

Теперь метод называется не name а speakTheName и реализовывает "Называю свое имя при прикосновении" Такая комната ужасов получается, вилки летают и некоторые вещи разговаривают, так заказчик захотел, что я могу поделать)

2020-11-30 09:34 UTC, Alexis220382 requested changes
Леша, пересмотри еще раз все, что написал

2020-11-30 09:34 UTC, Alexis220382 commented on src/suboch/Fork.java
>          System.out.println("Я вилка, я взлетела");
Я бы предложил сделать немного по другому. Сейчас это смотрится, как два действия в одном. И имя свое печатает и озвучивает еще какое-то действие. Есть предложения?

2020-11-30 09:34 UTC, Alexis220382 commented on src/suboch/Fridge.java
> +    public void speakTheName() {
`printName()` на мой взгляд, было бы более актуальное название для сего поведения

2020-11-30 09:34 UTC, Alexis220382 commented on src/suboch/Info.java
> +    void speakTheName();
👆

2020-11-30 09:34 UTC, Alexis220382 commented on src/suboch/Lamp.java
> +        System.out.println("Называю свое имя при прикосновении");
В одно и то же поведение вложен разный смысл. В одном классе метод говорит, что он вилка, а тут метод говорит, что называет имя, хотя реализован в конкретном классе Лампа. Почему бы тут тоже не сделать реализацию с текстом "Я лампа"?
Это путает. Если ты ожидаешь от названия поведения, что оно будет называть имя, то оно должно называть имя, где бы оно (это поведение) не реализовывалось

2020-11-30 09:34 UTC, Alexis220382 commented on src/suboch/MicrowaveOven.java
> +    public void speakTheName() {
Название метода (комментировал выше)
По содержанию метода тоже комментировал выше

2020-11-30 09:34 UTC, Alexis220382 commented on src/suboch/MicrowaveOven.java
>      public void name() {
Какой смысл иметь два метода `speakTheName()` и `name()` по идее они должны делать одно и тоже. Плюс это то, что я просил вынести в интерфейс

2020-11-30 09:34 UTC, Alexis220382 commented on src/suboch/TVset.java
> +        System.out.println("Называю свое имя при прикосновении");
Тоже самое (название и содержание)

2020-12-03 12:44 UTC, Alex8185 commented on src/suboch/Fork.java
>          System.out.println("Я вилка, я взлетела");
Я по этому поводу возмущался уже, я после того, как увидел посыл не заморачиваться над методами, над ними и не заморачивался, а потом получил за это же замечания

2020-12-03 12:53 UTC, Alex8185 commented on src/suboch/Info.java
> +    void speakTheName();
verry good

2020-12-03 12:57 UTC, Alex8185 commented on src/suboch/Lamp.java
> +        System.out.println("Называю свое имя при прикосновении");
Писал выше, что это может быть любая фраза, а фраза "Называю свое имя при прикосновении" она универсальная, любой предмет может назвать свое имя.

2020-12-03 12:57 UTC, Alex8185 commented on src/suboch/MicrowaveOven.java
> +    public void speakTheName() {
Ответил

2020-12-03 13:03 UTC, Alex8185 commented on src/suboch/MicrowaveOven.java
>      public void name() {
Писал выше, я программист, я так задумал, это сейчас разные методы, маслом -масляным они станут если переименовать speakTheName.
В интерфейс вынес name( );

2020-12-03 13:03 UTC, Alex8185 commented on src/suboch/TVset.java
> +        System.out.println("Называю свое имя при прикосновении");
ок

2020-12-03 13:30 UTC, Alexis220382 commented on src/suboch/MicrowaveOven.java
>      public void name() {
Ты программист, нет вопросов, но я же не просто так пытаюсь навести на мысль.
А если не переименовывать, а вообще убрать speakTheName() и name(), и оставить только один новый printName()?
На мой взгляд, он по наименованию больше подходит к его обязанности

2020-12-03 16:02 UTC, Alex8185 commented on src/suboch/TVset.java
> +        System.out.println("Называю свое имя при прикосновении");
И свои эти два убери, они меня накаляют, я же сказал, я не настаиваю, но только один мой метод!))))))))))))))))))

2020-12-03 16:20 UTC, Alexis220382 requested changes
Увидел ответы, которые меня не убедили.
Ни одного исправления не увидел.

2020-12-03 16:20 UTC, Alexis220382 commented on src/suboch/Fork.java
>          System.out.println("Я вилка, я взлетела");
Немного не понятна принципиальная позиция по этому поводу, а особенно какую пользу она принесет в обучении, но настаивать не буду.
Кстати, настоящие настройки GitHub, позволяют смержить пул-реквест даже не получив аппрува на это🙂

2020-12-03 16:20 UTC, Alexis220382 commented on src/suboch/Lamp.java
> +        System.out.println("Называю свое имя при прикосновении");
В том-то все дело, что фраза универсальная и применима не только к лампе.
В таком случае этот метод можно было бы реализовать в абстрактном классе, который является вершиной иерархии, в которую входит лампа и не дублировать у всех уго наследников и пользоваться общим методом абстрактного класса.
Но тогда конкретные классы будут лишены индивидуальности.
Задача состояла в том, чтобы дать возможность пользователю иерархии получать наименование текущего объекта, реализация которого скрыта.

2020-12-03 16:20 UTC, Alexis220382 commented on src/suboch/MicrowaveOven.java
>      public void name() {
Задача состояла в том, чтобы дать возможность пользователю иерархии получать наименование текущего объекта, реализация которого скрыта.

2020-12-03 18:20 UTC, Alexis220382 approved these changes
Аппрув, ..... на твое усмотрение то, что я просил устранить, но оно так и не было устранено

На всякий случай список:
- действия, не предусмотренные названием метода
- непонятно для чего добавленное слово static
- лишние пробелы перед названием класса
- и методы с пустым телом внутри

2020-12-03 19:39 UTC, merged